// resources/js/client/components/builder/Bundle.vue
<template>
  <a-row type="flex" justify="space-between" class="overflow-hidden">
    <a-col :md="11" :sm="24">
      <music-icon v-if="getExtra('audio')" :played="audioContext_played" width="300" height="300"/>
      <editor-content v-if="tiptap.content" class="editor__content" :editor="tiptap.content"
                      ref="content" :style="contentStyle"/>
      <br>
      <span>{{ note }}</span>
    </a-col>
    <a-divider type="vertical" orientation="center" :style="{ height: 'auto' }"/>
    <a-col :md="11" :sm="24" :style="{ overflowY: 'auto', maxHeight: '65vh' }" ref="children-wrapper">
      <div v-for="(subItem, i) in subItems" :key="i">
        <a-divider type="horizontal" :ref="'child-active-'+subItem.id"/>
        <a-button block :type="activeItemId === subItem.id ? 'danger' : 'dashed'"><b>{{subItem.label}}</b></a-button>
        <slot name="single" :item="subItem" :value="resolveValue(subItem)"></slot>
      </div>
      <a-divider type="horizontal"/>
      <arrow-navigation/>
    </a-col>
  </a-row>
</template>

<script>
  import extraMixins from '../../extra/mixins'
  import MusicIcon from './part/MusicIcon'
  import { mapState, mapGetters } from 'vuex'
  import _ from 'lodash'
  import {
    Blockquote, Bold,
    BulletList,
    HardBreak,
    Heading, History,
    HorizontalRule, Italic, Link,
    ListItem,
    OrderedList, Strike,
    TodoItem, TodoList, Underline
  } from "tiptap-extensions";
  import {Editor, EditorContent} from "tiptap";
  import ArrowNavigation from "../perform/ArrowNavigation";

  const extensions = [
    new Blockquote(), new BulletList(), new HardBreak(), new Heading({ levels: [1, 2, 3] }), new HorizontalRule(),
    new ListItem(), new OrderedList(), new TodoItem(), new TodoList(), new Link(), new Bold(),
    new Italic(), new Strike(), new Underline(), new History(),
  ]

  export default {
    name: "Bundle",
    data: () => ({
      tiptap: {
        content: null,
        subContent: null,
      },
    }),
    props: {
      item: {
        required: true,
        type: Object
      },
    },
    computed: {
      ...mapState('exam/perform', {
        activeItemId: state => state.active.item
      }),
      ...mapGetters('exam/perform', {
        section: 'activeSection'
      }),
      groupLabelBy: function () {
        let sign = this.getExtra('group_by')
        if (sign.indexOf(',') !== -1) {
          return sign.split(',')
        }
        return [sign]
      },
      isGroupParent: function () {
        return (label) => this.groupLabelBy.some(sign => _.startsWith(label, sign))
      },
      groupedItems: function () {
        const groupByLabel = this.groupLabelBy
        if (! groupByLabel) {
          console.warn("group by extra is missing in bundle type")
          return []
        }

        const results = []
        const items = this.section.items

        // we will get index of activeItem
        const activeItemIndex = items.findIndex(i => i.id === this.item.id)
        // then loop it from top to bottom
        for (let i = activeItemIndex; i < items.length; i++) {
          if (this.isGroupParent(items[i].label) && i !== activeItemIndex)
            break
          results.push(items[i])
        }
        if (! this.isGroupParent(this.item.label)) {
          // because of active item label is now same with groupByLabel is indicate that active item is pinched
          // we will loop it from bottom to top
          let i = activeItemIndex
          do {
            i--
            results.push(items[i])
          } while (! this.isGroupParent(items[i].label))
        }

        return results.sort((a, b) => a.order - b.order)
      },
      itemParent: function () {
        // itemParent is a head labeled from group by and should be available at grouped items
        return this.groupedItems.find(i => this.isGroupParent(i.label))
      },
      subItems: function () {
        return this.groupedItems.filter(i => ! this.isGroupParent(i.label))
      },
      disablePlugin: function () {
        return this.itemParent?.id !== this.item.id
      },
      note: function () {
        if (! this.subItems || this.subItems.length === 0)
          return ''

        if (this.subItems.length === 1)
          return 'numbers : ' + this.subItems[0].label

        return 'numbers : ' + this.subItems[0].label + ' - ' + this.subItems[this.subItems.length - 1].label
      }
    },
    mixins: [ extraMixins ],
    components: { EditorContent, MusicIcon, ArrowNavigation },
    watch: {
      item: function () {
        this.bootBundle()
      }
    },
    methods: {
      bootBundle () {
        if (this.tiptap.content !== null) {
          this.tiptap.content.setContent(this.item.content?.replaceAll(' ', '&nbsp;'))
        }

        if (this.tiptap.subContent !== null) {
          this.tiptap.subContent.setContent(((! isNaN(this.item.label) ? this.item.label + '. ' : '') + this.item['sub_content'])?.replaceAll(' ', '&nbsp;'))
        } else {
          this.tiptap.subContent = new Editor({
            extensions,
            content: ((! isNaN(this.item.label) ? this.item.label + '. ' : '') + this.item['sub_content'])?.replaceAll(' ', '&nbsp;'),
            editable: false,
          })
        }

        (this.disablePlugin) ? this.resetPluginData() : this.bootPlugins()

        this.scrollToActive()
      },
      resolveValue (item) {
        return _.get(
          _.get(item, 'attempts', []).find(a => _.get(a, 'attempt_number', -1) === _.get(this.section, 'attempts')),
          'answer',
          null
        )
      },
      scrollToActive () {
        let offsetTop = 0
        if (this.$refs['child-active-'+this.activeItemId]) {
          offsetTop = this.$refs['child-active-'+this.activeItemId][0].$el?.offsetTop
        }

        this.$refs['children-wrapper'].$el.scroll({
          top: offsetTop,
          left: 0,
          behavior: 'smooth'
        })
      }
    },
    mounted () {
      if (this.item.content !== null) {
        this.tiptap.content = new Editor({
          extensions,
          content: this.item.content?.replaceAll(' ', '&nbsp;'),
          editable: false,
        })
      }

      if (this.item['sub_content'] !== null) {
        this.tiptap.subContent = new Editor({
          extensions,
          content: this.item['sub_content']?.replaceAll(' ', '&nbsp;'),
          editable: false,
        })
      }

      this.bootBundle()
    }
  }
</script>

<style scoped>

</style>

// resources/js/client/components/builder/Bundle.jsx
import React, { useEffect, useRef, useState } from 'react';
import { useSelector } from 'react-redux';

import MusicIcon from './part/MusicIcon';
import ArrowNavigation from '../performs/ArrowNavigation';
import useExtraFeatures from '../../hooks/useExtraFeatures';
import { getActiveSection } from '../../slices/performSlice';

import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Link from '@tiptap/extension-link';
import Underline from '@tiptap/extension-underline';
import Subscript from '@tiptap/extension-subscript';
import Superscript from '@tiptap/extension-superscript';
import TaskList from '@tiptap/extension-task-list';
import TaskItem from '@tiptap/extension-task-item';

import { Row, Col, Divider, Button } from 'antd';
import _ from 'lodash';

const extensions = [
    StarterKit.configure({
        heading: {
            levels: [1, 2, 3, 4, 5],
        },
    }),
    Link,
    Underline,
    Subscript,
    Superscript,
    TaskList,
    TaskItem.configure({
        nested: true, // Mengizinkan daftar tugas bersarang
    }),
];

const Bundle = ({ item, children }) => {
    const [tiptap, setTiptap] = useState({
        content: null,
        subContent: null,
    });

    const {
        getExtra,
        audioContext_played,
        audioContext_instance,
        line_count_context,
        resetPluginData,
        bootPlugins,
        contentStyle
    } = useExtraFeatures(item);

    const activeItemId = useSelector(state => state.perform.active.item);
    const section = useSelector(getActiveSection);
    const childrenWrapperRef = useRef(null);

    const groupLabelBy = () => {
        const sign = getExtra('group_by');
        return sign.includes(',') ? sign.split(',') : [sign];
    };

    const isGroupParent = (label) => {
        return groupLabelBy().some(sign => _.startsWith(label, sign));
    };

    const groupedItems = () => {
        const results = [];
        const items = section.items;
        const activeItemIndex = items.findIndex(i => i.id === item.id);

        for (let i = activeItemIndex; i < items.length; i++) {
            if (isGroupParent(items[i].label) && i !== activeItemIndex)
                break;
            results.push(items[i]);
        }
        if (!isGroupParent(item.label)) {
            let i = activeItemIndex;
            do {
                i--;
                results.push(items[i]);
            } while (!isGroupParent(items[i].label));
        }
        return results.sort((a, b) => a.order - b.order);
    };

    const itemParent = () => groupedItems().find(i => isGroupParent(i.label));
    const subItems = () => groupedItems().filter(i => !isGroupParent(i.label));
    const disablePlugin = () => itemParent()?.id !== item.id;

    const editor1 = useEditor({
        extensions,
        content: ((!isNaN(item.label) ? item.label + '. ' : '') + item['sub_content'])?.replaceAll(' ', '&nbsp;'),
        editable: false,
    })

    const editor2 = useEditor({
        extensions,
        content: item.content?.replaceAll(' ', '&nbsp;'),
        editable: false,
    })

    const editor3 = useEditor({
        extensions,
        content: item['sub_content']?.replaceAll(' ', '&nbsp;'),
        editable: false,
    })

    const note = () => {
        if (!subItems() || subItems().length === 0)
            return '';
        if (subItems().length === 1)
            return 'numbers : ' + subItems()[0].label;
        return 'numbers : ' + subItems()[0].label + ' - ' + subItems()[subItems().length - 1].label;
    };

    const bootBundle = () => {
        if (tiptap.content !== null) {
            tiptap.content.commands.setContent(item.content?.replaceAll(' ', '&nbsp;'));
        }
        if (tiptap.subContent !== null) {
            tiptap.subContent.commands.setContent(((!isNaN(item.label) ? item.label + '. ' : '') + item['sub_content'])?.replaceAll(' ', '&nbsp;'));
        } else {
            setTiptap(prevState => ({
                ...prevState,
                subContent: editor1,
            }));
        }
        disablePlugin() ? resetPluginData() : bootPlugins();
        scrollToActive();
    };

    const resolveValue = (item) => {
        return _.get(
            _.get(item, 'attempts', []).find(a => _.get(a, 'attempt_number', -1) === _.get(section, 'attempts')),
            'answer',
            null
        );
    };

    const scrollToActive = () => {
        let offsetTop = 0;
        if (childrenWrapperRef.current && childrenWrapperRef.current[`child-active-${activeItemId}`]) {
            offsetTop = childrenWrapperRef.current[`child-active-${activeItemId}`].offsetTop;
        }
        childrenWrapperRef.current.scroll({
            top: offsetTop,
            left: 0,
            behavior: 'smooth',
        });
    };

    useEffect(() => {
        if (item.content !== null) {
            setTiptap(prevState => ({
                ...prevState,
                content: editor2,
            }));
        }
        if (item.subContent !== null) {
            setTiptap(prevState => ({
                ...prevState,
                subContent: editor3,
            }));
        }
        bootBundle();
    }, [item]);

    return (
        <Row type="flex" justify="space-between" className="overflow-hidden">
            <Col md={11} sm={24}>
                {getExtra('audio') && <MusicIcon played={audioContext_played} width={300} height={300} />}
                {tiptap.content && <EditorContent editor={tiptap.content} className="editor__content" ref={contentRef} style={contentStyle} />}
                <br />
                <span>{note()}</span>
            </Col>
            <Divider type="vertical" orientation="center" style={{ height: 'auto' }} />
            <Col md={11} sm={24} style={{ overflowY: 'auto', maxHeight: '65vh' }} ref={childrenWrapperRef}>
                {subItems().map((subItem, i) => (
                    <div key={i}>
                        <Divider type="horizontal" ref={`child-active-${subItem.id}`} />
                        <Button block type={activeItemId === subItem.id ? 'danger' : 'dashed'}><b>{subItem.label}</b></Button>
                        {children(resolveValue(subItem))}
                    </div>
                ))}
                <Divider type="horizontal" />
                <ArrowNavigation />
            </Col>
        </Row>
    );
};

export default Bundle;
