// resources/js/client/components/perform/Countdown.vue
<template>
  <span>{{timeFormatted}}</span>
</template>

<script>

  export default {
    name: "Countdown",
    props: {
      availableTime: {
        required: true,
        type: Number
      },
      gap: {
        type: Number,
        default: 5
      },
      freeze: {
        type: Boolean,
        default: false
      }
    },
    data: () => ({
      time: 0,
    }),
    computed: {
      timeFormatted: function () {
        function sec2time(timeInSeconds) {
          const pad = (num, size) => ('000' + num).slice(size * -1),
            time = parseInt(timeInSeconds),
            minutes = Math.floor(time / 60) % 60,
            seconds = Math.floor(time - minutes * 60)

          return pad(minutes, 2) + ':' + pad(seconds, 2)
        }
        return sec2time(this.time)
      }
    },
    watch: {
      availableTime: function (newValue) {
        this.time = newValue
      },
      time: function (newValue) {
        if (newValue % this.gap === 0) {
          this.$emit('every', this.gap)
        }

        if (newValue <= 0) {
          this.$emit('timeout')
        }
      }
    },
    methods: {
      decrementTime () {
        this.time > 0 ? ! this.freeze ? this.time-- : null : null

        // call recursively after 1 second
        setTimeout(() => this.decrementTime(), 1000)
      },
      reset () {
        this.time = this.availableTime
      }
    },
    mounted () {
      this.decrementTime()
    }
  }
</script>

<style scoped>

</style>

// resources/js/client/components/performs/Countdown.jsx
import React, { useEffect, useState } from 'react';

const Countdown = ({ availableTime, gap = 5, freeze = false }) => {
    const [time, setTime] = useState(availableTime);

    const sec2time = (timeInSeconds) => {
        const pad = (num, size) => ('000' + num).slice(size * -1);
        const minutes = Math.floor(timeInSeconds / 60) % 60;
        const seconds = Math.floor(timeInSeconds - minutes * 60);
        return `${pad(minutes, 2)}:${pad(seconds, 2)}`;
    };

    useEffect(() => {
        setTime(availableTime);
    }, [availableTime]);

    useEffect(() => {
        if (time > 0) {
            const timer = setTimeout(() => {
                if (!freeze) {
                    setTime((prevTime) => {
                        if (prevTime % gap === 0) {
                            // Emit 'every' event
                            console.log('every', gap);
                        }
                        if (prevTime <= 1) {
                            // Emit 'timeout' event
                            console.log('timeout');
                        }
                        return prevTime - 1;
                    });
                }
            }, 1000);
            return () => clearTimeout(timer);
        }
    }, [time, freeze, gap]);

    const reset = () => {
        setTime(availableTime);
    };

    return <span>{sec2time(time)}</span>;
};

export default Countdown;
