// resources/js/client/components/perform/ItemNavigation.vue
<template>
  <a-drawer
    v-if="activeSection !== null && activeItem !== null"
    placement="right"
    :closable="false"
    @close="close"
    :visible="visible">
    <a-collapse :accordion="true" :activeKey="activeSection.id"
                expandIconPosition="right" :bordered="false">
      <a-collapse-panel v-for="section in sections" :header="section.config.title"
                        :key="section.id" :disabled="section.id !== activeSection.id">
        <a-row type="flex" justify="space-between">
          <a-col v-for="item in section.items" :key="item.id" :md="item.label.length > 4 ? 24 : 11" :sm="24">
            <a-button block @click="changeActiveItem(item.id)" :class="getAnsweredClass(item)"
                      :disabled="(itemDuration && item.id !== activeItem.id) || (section.id !== activeSection.id)"
                      :type="getTypeButton(item)">
              {{item.label}} <span v-if="getAnsweredClass(item).length > 0">&nbsp;<a-icon type="check-circle" /></span>
            </a-button>
          </a-col>
        </a-row>
      </a-collapse-panel>
    </a-collapse>
  </a-drawer>
</template>

<script>
  import { mapGetters, mapMutations } from 'vuex'
  import { MUTATION as PERFORM_MUTATION } from '../../store/modules/exam/perform'

  export default {
    name: "ItemNavigation",
    props: {
      visible: {
        required: true
      }
    },
    computed: mapGetters('exam/perform', {
      sections: 'sections',
      activeSection: 'activeSection',
      activeItem: 'activeItem',
      itemDuration: 'itemDuration',
      sectionItemsAnswered: 'sectionItemsAnswered',
    }),
    watch: {
      activeSection: function () {
        this.close()
      },
      activeItem: function () {
        this.close()
      }
    },
    methods: {
      ...mapMutations('exam/perform', {
        changeActive: PERFORM_MUTATION.CHANGE_ACTIVE
      }),
      getAnsweredClass (item) {
        if (item !== null && this.sectionItemsAnswered.findIndex(id => item.id === id) !== -1) {
          return ['answered']
        }
        return []
      },
      getTypeButton (item) {
        return item.id !== this.activeItem.id ? 'default' : 'primary'
      },
      changeActiveItem (itemId) {
        if (! this.itemDuration)
          this.changeActive({ item: itemId })
      },
      close () {
        this.$emit('close')
      }
    }
  }
</script>

<!--suppress CssUnusedSymbol -->
<style scoped>
  .ant-col {
    margin: 0.25em auto
  }

  .ant-col-md-24 > button {
    height: auto;
    white-space: normal;
    font-size: unset;
  }

  .answered {
    border-color: cornflowerblue;
  }
</style>

// resources/js/client/components/performs/ItemNavigation.jsx
import React, { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Drawer, Collapse, Row, Col, Button, Icon } from 'antd';
import { getSection, getActiveSection, getActiveItem, getItemDuration, getSectionItemsAnswered, change_active } from '../../slices/performSlice';
import CheckCircleOutlineRoundedIcon from '@mui/icons-material/CheckCircleOutlineRounded';

const ItemNavigation = ({ visible, onClose }) => {
    const dispatch = useDispatch();

    const sections = useSelector(getSection)
    const activeSection = useSelector(getActiveSection)
    const activeItem = useSelector(getActiveItem)
    const itemDuration = useSelector(getItemDuration)
    const sectionItemsAnswered = useSelector(getSectionItemsAnswered)

    useEffect(() => {
        if (activeSection !== null) {
            close();
        }
    }, [activeSection]);

    useEffect(() => {
        if (activeItem !== null) {
            close();
        }
    }, [activeItem]);

    const getAnsweredClass = (item) => {
        return item !== null && sectionItemsAnswered.includes(item.id) ? ['answered'] : [];
    };

    const getTypeButton = (item) => {
        return item.id !== activeItem.id ? 'default' : 'primary';
    };

    const changeActiveItem = (itemId) => {
        if (!itemDuration) {
            dispatch(change_active({ item: itemId }));
        }
    };

    const close = () => {
        onClose();
    };

    return (
        <Drawer
            open={visible && activeSection !== null && activeItem !== null}
            placement="right"
            closable={false}
            onClose={close}
        >
            <Collapse accordion activeKey={activeSection?.id} expandIconPosition="end" bordered={false}>
                {sections.map(section => (
                    <Collapse.Panel header={section.config.title} key={section.id} collapsible={section.id !== activeSection.id ? "disabled" : ""}>
                        <Row justify="space-between">
                            {section.items.map(item => (
                                <Col key={item.id} md={item.label.length > 4 ? 24 : 11} sm={24}>
                                    <Button
                                        block
                                        onClick={() => changeActiveItem(item.id)}
                                        className={getAnsweredClass(item).join(' ')}
                                        disabled={(itemDuration && item.id !== activeItem.id) || (section.id !== activeSection.id)}
                                        type={getTypeButton(item)}
                                    >
                                        {item.label} {getAnsweredClass(item).length > 0 && <CheckCircleOutlineRoundedIcon />}
                                    </Button>
                                </Col>
                            ))}
                        </Row>
                    </Collapse.Panel>
                ))}
            </Collapse>
        </Drawer>
    );
};

export default ItemNavigation;
