// resources/js/client/views/perform/PerformWaiting.jsx
import React, { useEffect } from 'react'
import { useSelector } from 'react-redux'
import { useNavigate } from 'react-router-dom'
import { CircularProgress } from '@mui/material'

import { getIsStarted, getActiveExam } from '../../slices/examSlice'

const PerformWaiting = () => {
  const navigate = useNavigate()
  const isStarted = useSelector(getIsStarted)
  const activeExam = useSelector(getActiveExam)

  useEffect(() => {
    if (isStarted) {
      navigate("/client/perform/tackle")
    }
  }, [isStarted, navigate])

  return (
    <div className="flex items-center">
      <div className="w-1/2">
        <h1 className="text-2xl font-bold">{activeExam.name}</h1>
        <h1 className="text-xl">WAITING <b>PROCTOR</b> TO START AN EXAM</h1>
      </div>
      <div className="w-1/2 flex justify-center">
        <CircularProgress />
      </div>
    </div>
  )
}

export default PerformWaiting

// resources/js/client/views/perform/PerformWaiting.vue
<template>
  <!--suppress HtmlDeprecatedAttribute -->
  <a-row type="flex" align="middle">
    <a-col :span="12">
      <h1><b>{{activeExam.name}}</b></h1>
      <h1>WAITING <b>PROCTOR</b> TO START AN EXAM</h1>
    </a-col>
    <a-col :span="12">
      <loading-icon/>
    </a-col>
  </a-row>
</template>

<script>
  import { mapGetters } from 'vuex'
  import LoadingIcon from '../../components/perform/LoadingIcon'

  export default {
    name: "PerformWaiting",
    components: { LoadingIcon },
    computed: {
      ...mapGetters('exam', ['isStarted', 'activeExam'])
    },
    watch: {
      'isStarted': function (newValue) {
        if (newValue)
          this.$router.push({ name: 'perform.tackle' })
      }
    }
  }
</script>

<style scoped>

</style>
